services:
  - type: web
    name: nekohelx
    env: docker
    image: ghcr.io/m1k1o/neko/firefox:latest
    plan: free
    autoDeploy: true
    envVars:
      - key: NEKO_DESKTOP_SCREEN
        value: 1920x1080@30
      - key: NEKO_MEMBER_MULTIUSER_USER_PASSWORD
        value: neko
      - key: NEKO_MEMBER_MULTIUSER_ADMIN_PASSWORD
        value: admin
      - key: NEKO_WEBRTC_EPR
        value: 52000-52100
      - key: NEKO_WEBRTC_ICELITE
        value: 1
    ports:
      - 8080
