name: Test Client Build

on:
  pull_request:
    branches:
      - master
    paths:
      - client/**
      - .github/workflows/client_test.yml

jobs:
  client_test:
    name: Test Client Build
    uses: ./.github/workflows/client_build.yml
    with:
      # Do not upload artifacts for test builds
      with-arifact: false
