name: Build and Publish Client Artifacts

on: {} # Temporarily disable the trigger to avoid unnecessary builds

#on:
#  pull_request: # Change to push when ready to deploy
#    branches:
#      - master
#    paths:
#      - client/**
#      - .github/workflows/client_build.yml

jobs:
  client_build:
    name: Build and Publish Client Artifacts
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        working-directory: ./client
        run: npm ci

      - name: Build client
        working-directory: ./client
        run: npm run build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: client
          path: client/dist
