name: "nvidia gpu supported images"

on:
  push:
    tags:
      - 'v*'

jobs:
  build-base:
    uses: ./.github/workflows/image_base.yml
    with:
      flavor: nvidia
      platforms: linux/amd64
      dockerfile: Dockerfile.nvidia
    secrets:
      GHCR_ACCESS_TOKEN: ${{ secrets.GHCR_ACCESS_TOKEN }}

  build-apps:
    uses: ./.github/workflows/image_app.yml
    needs: [ build-base ]
    strategy:
      # Will build all images even if some fail.
      fail-fast: false
      matrix:
        include:
          - name: firefox
            dockerfile: Dockerfile.nvidia
          - name: brave
            dockerfile: Dockerfile.nvidia
          - name: chromium
            dockerfile: Dockerfile.nvidia
          - name: google-chrome
            dockerfile: Dockerfile.nvidia
          - name: microsoft-edge
            dockerfile: Dockerfile.nvidia
    with:
      name: ${{ matrix.name }}
      dockerfile: ${{ matrix.dockerfile }}
      flavor: nvidia
      platforms: linux/amd64
    secrets:
      GHCR_ACCESS_TOKEN: ${{ secrets.GHCR_ACCESS_TOKEN }}
