name: "intel gpu supported images"

on:
  push:
    tags:
      - 'v*'

jobs:
  build-base:
    uses: ./.github/workflows/image_base.yml
    with:
      flavor: intel
      platforms: linux/amd64
      dockerfile: Dockerfile.intel
    secrets: inherit

  build-apps:
    uses: ./.github/workflows/image_app.yml
    needs: build-base
    strategy:
      # Will build all images even if some fail.
      fail-fast: false
      matrix:
        include:
          - name: firefox
          - name: waterfox
          - name: chromium
          - name: google-chrome
          - name: ungoogled-chromium
          - name: microsoft-edge
          - name: brave
          - name: vivaldi
          - name: opera
          - name: tor-browser
          - name: remmina
          - name: vlc
          - name: xfce
          - name: kde
    with:
      name: ${{ matrix.name }}
      dockerfile: ${{ matrix.dockerfile }}
      flavor: intel
      platforms: linux/amd64
    secrets: inherit
