name: Test Server Build

on:
  pull_request:
    branches:
      - master
    paths:
      - server/**
      - .github/workflows/server_test.yml

jobs:
  server_test:
    name: Test Server Build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./server
