name: Build and Deploy Webpage to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - webpage/**
      - .github/workflows/webpage_deploy.yml

jobs:
  webpage_build:
    name: Build and Deploy Webpage to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: webpage/package-lock.json

      - name: Install dependencies
        working-directory: ./webpage
        run: npm ci

      - name: Build webpage
        working-directory: ./webpage
        run: npm run build

      - name: Upload Build Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          artifact-name: github-pages
          path: ./webpage/build

  webpage_deploy:
    name: Deploy to GitHub Pages
    needs: webpage_build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
